server:
  port: 9099
spring:
  application:
    name: auth-microservice
  config:
    import: optional:file:.env[.properties]
  main:
    allow-circular-references: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

security:
  jwt:
    secret: ${JWT_SECRET}
    access: 1
    refresh: 30

rest:
  userServiceLink: ${USER_SERVICE_LINK}
