server:
  port: 9098

spring:
  application:
    name: invest-microservice
  config:
    import: optional:file:.env[.properties]

secret:
  token: ${TOKEN}

rest:
  userServiceLink: ${USER_SERVICE_LINK}
  createAccountLink: ${CREATE_ACCOUNT_LINK}
  accountServiceLink: ${ACCOUNT_SERVICE_LINK}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
