server:
  port: 9097
spring:
  application:
    name: crud-microservice
  config:
    import: optional:file:.env[.properties]
  main:
    allow-circular-references: true

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
#    properties:
#      hibernate.default_schema: ${HIBERNATE_SCHEMA}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}